config/routes.rb
Rails.application.routes.draw do
  resources :experiences do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :certifications

  resources :educations

  resources :skills do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :profiles do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_posts

  resources :projects do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_types

  resources :job_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'profiles#index'
  
  
  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base
end

app/controllers/job_categories_controller.rb
class JobCategoriesController < ApplicationController
  before_action :set_job_category, only: [:show, :edit, :update, :destroy]

  # GET /job_categories
  # GET /job_categories.json
  def index
    @job_categories = JobCategory.all
  end

  # GET /job_categories/1
  # GET /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @job_category = JobCategory.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories
  # POST /job_categories.json
  def create
    @job_category = JobCategory.new(job_category_params)

    respond_to do |format|
      if @job_category.save
        format.html { redirect_to @job_category, notice: 'Job category was successfully created.' }
        format.json { render :show, status: :created, location: @job_category }
      else
        format.html { render :new }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1
  # PATCH/PUT /job_categories/1.json
  def update
    respond_to do |format|
      if @job_category.update(job_category_params)
        format.html { redirect_to @job_category, notice: 'Job category was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_category }
      else
        format.html { render :edit }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1
  # DELETE /job_categories/1.json
  def destroy
    @job_category.destroy
    respond_to do |format|
      format.html { redirect_to job_categories_url, notice: 'Job category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_category
      @job_category = JobCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_category_params
      params.require(:job_category).permit(:category)
    end
end

app/helpers/job_categories_helper.rb
module JobCategoriesHelper
end

app/views/job_categories/_form.html.erb
<%= form_for @job_category, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :category, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  job_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/job_categories/edit.html.erb
<%- model_class = JobCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => JobCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/job_categories/index.html.erb
<%- model_class = JobCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => JobCategory %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @job_categories.each do |job_category| %>
      <tr>
        <td><%= job_category.id %></td>
        <td><%= job_category.category %></td>
        <td><%=l job_category.created_at, format: :long %></td>
        <td>
          <%= link_to job_category_path(job_category), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to job_category_path(job_category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_category_path,
            :class => 'btn btn-primary' %>

app/views/job_categories/new.html.erb
<%- model_class = JobCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => JobCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/job_categories/show.html.erb
<%- model_class = JobCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => JobCategory %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:category) %></dt>
      <dd><pre class="prettyprint"><%= @job_category.category %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              job_categories_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_category_path(@job_category), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_category_path(@job_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>