config/routes.rb
Rails.application.routes.draw do
  resources :experiences do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :certifications

  resources :educations

  resources :skills do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :profiles do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_posts

  resources :projects do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_types

  resources :job_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'profiles#index'
  
  
  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :profile
  validates_formatting_of :certification_url, using: :url
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show, :edit, :update, :destroy]

  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = Certification.all
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
  end

  # GET /certifications/new
  def new
    @certification = Certification.new
  end

  # GET /certifications/1/edit
  def edit
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification = Certification.new(certification_params)

    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification, notice: 'Certification was successfully created.' }
        format.json { render :show, status: :created, location: @certification }
      else
        format.html { render :new }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certifications/1
  # PATCH/PUT /certifications/1.json
  def update
    respond_to do |format|
      if @certification.update(certification_params)
        format.html { redirect_to @certification, notice: 'Certification was successfully updated.' }
        format.json { render :show, status: :ok, location: @certification }
      else
        format.html { render :edit }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification.destroy
    respond_to do |format|
      format.html { redirect_to certifications_url, notice: 'Certification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification
      @certification = Certification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certification_params
      params.require(:certification).permit(:profile_id, :certification_name, :certification_authority, :certification_url, :certification_image)
    end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.erb
<%= form_for @certification, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :certification_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :certification_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :certification_authority, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :certification_authority, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :certification_url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :certification_url, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :certification_image, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :certification_image, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  certifications_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<%- model_class = Certification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Certification %></h1>
</div>
<%= render :partial => 'form' %>

app/views/certifications/index.html.erb
<%- model_class = Certification -%>
<div class="page-header">
  <h1><%=t '.title', :default => Certification %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:certification_name) %></th>
      <th><%= model_class.human_attribute_name(:certification_authority) %></th>
      <th><%= model_class.human_attribute_name(:certification_url) %></th>
      <th><%= model_class.human_attribute_name(:certification_image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @certifications.each do |certification| %>
      <tr>
        <td><%= certification.id %></td>
        <td><%= certification.certification_name %></td>
        <td><%= certification.certification_authority %></td>
        <td><%= certification.certification_url %></td>
        <td><%= certification.certification_image %></td>
        <td><%=l certification.created_at, format: :long %></td>
        <td>
          <%= link_to certification_path(certification), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to certification_path(certification), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_certification_path,
            :class => 'btn btn-primary' %>

app/views/certifications/new.html.erb
<%- model_class = Certification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Certification %></h1>
</div>
<%= render :partial => 'form' %>

app/views/certifications/show.html.erb
<%- model_class = Certification -%>
<div class="page-header">
  <h1><%=t '.title', :default => Certification %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:certification_name) %></dt>
      <dd><pre class="prettyprint"><%= @certification.certification_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:certification_authority) %></dt>
      <dd><pre class="prettyprint"><%= @certification.certification_authority %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:certification_url) %></dt>
      <dd><pre class="prettyprint"><%= @certification.certification_url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:certification_image) %></dt>
      <dd><pre class="prettyprint"><%= @certification.certification_image %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              certifications_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_certification_path(@certification), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              certification_path(@certification),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>