config/routes.rb
Rails.application.routes.draw do
  resources :experiences do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :certifications

  resources :educations

  resources :skills do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :profiles do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_posts

  resources :projects do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_types

  resources :job_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'profiles#index'
  
  
  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :user
  has_many :job_types
  validates_formatting_of :contact_email, using: :email
  validates_formatting_of :website, using: :url
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_job_post, only: [:show, :edit, :update, :destroy]

  # GET /job_posts
  # GET /job_posts.json
  def index
    @job_posts = JobPost.all
  end

  # GET /job_posts/1
  # GET /job_posts/1.json
  def show
  end

  # GET /job_posts/new
  def new
    @job_post = JobPost.new
  end

  # GET /job_posts/1/edit
  def edit
  end

  # POST /job_posts
  # POST /job_posts.json
  def create
    @job_post = JobPost.new(job_post_params)
    @job_post.user = current_user

    respond_to do |format|
      if @job_post.save
        format.html { redirect_to @job_post, notice: 'Job post was successfully created.' }
        format.json { render :show, status: :created, location: @job_post }
      else
        format.html { render :new }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_posts/1
  # PATCH/PUT /job_posts/1.json
  def update
    respond_to do |format|
      if @job_post.update(job_post_params)
        format.html { redirect_to @job_post, notice: 'Job post was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_post }
      else
        format.html { render :edit }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_posts/1
  # DELETE /job_posts/1.json
  def destroy
    @job_post.destroy
    respond_to do |format|
      format.html { redirect_to job_posts_url, notice: 'Job post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_post_params
      params.require(:job_post).permit(:company_name, :job_title, :salary, :location, :job_description, :job_benefits, :contact_email, :website, :phone, :user_id)
    end
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
<%= form_for @job_post, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :company_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job_title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :job_title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :salary, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :salary, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job_description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :job_description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job_benefits, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :job_benefits, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contact_email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.email_field :contact_email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :website, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :website, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  job_posts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/job_posts/edit.html.erb
<%- model_class = JobPost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => JobPost %></h1>
</div>
<%= render :partial => 'form' %>

app/views/job_posts/index.html.erb
<%- model_class = JobPost -%>
<div class="page-header">
  <h1><%=t '.title', :default => JobPost %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:job_title) %></th>
      <th><%= model_class.human_attribute_name(:salary) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:job_description) %></th>
      <th><%= model_class.human_attribute_name(:job_benefits) %></th>
      <th><%= model_class.human_attribute_name(:contact_email) %></th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @job_posts.each do |job_post| %>
      <tr>
        <td><%= job_post.id %></td>
        <td><%= job_post.company_name %></td>
        <td><%= job_post.job_title %></td>
        <td><%= job_post.salary %></td>
        <td><%= job_post.location %></td>
        <td><%= job_post.job_description %></td>
        <td><%= job_post.job_benefits %></td>
        <td><%= job_post.contact_email %></td>
        <td><%= job_post.website %></td>
        <td><%= job_post.phone %></td>
        <td><%=l job_post.created_at, format: :long %></td>
        <td>
          <%= link_to job_post_path(job_post), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to job_post_path(job_post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_post_path,
            :class => 'btn btn-primary' %>

app/views/job_posts/new.html.erb
<%- model_class = JobPost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => JobPost %></h1>
</div>
<%= render :partial => 'form' %>

app/views/job_posts/show.html.erb
<%- model_class = JobPost -%>
<div class="page-header">
  <h1><%=t '.title', :default => JobPost %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_name) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.company_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:job_title) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.job_title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:salary) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.salary %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:location) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:job_description) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.job_description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:job_benefits) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.job_benefits %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:contact_email) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.contact_email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:website) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.website %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @job_post.phone %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              job_posts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_post_path(@job_post), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_post_path(@job_post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>