config/routes.rb
Rails.application.routes.draw do
  resources :experiences do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :certifications

  resources :educations

  resources :skills do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :profiles do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_posts

  resources :projects do
  #->Prelang (voting/acts_as_votable)
  member do
    get "vote"
  end
end


  resources :job_types

  resources :job_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'profiles#index'
  
  
  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:school_name, :course, :field_of_study, :year_graduated, :profile_id)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for @education, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :school_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :school_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :course, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :course, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :field_of_study, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :field_of_study, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year_graduated, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :year_graduated, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  educations_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/educations/edit.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Education %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/index.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => Education %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:school_name) %></th>
      <th><%= model_class.human_attribute_name(:course) %></th>
      <th><%= model_class.human_attribute_name(:field_of_study) %></th>
      <th><%= model_class.human_attribute_name(:year_graduated) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.id %></td>
        <td><%= education.school_name %></td>
        <td><%= education.course %></td>
        <td><%= education.field_of_study %></td>
        <td><%= education.year_graduated %></td>
        <td><%=l education.created_at, format: :long %></td>
        <td>
          <%= link_to education_path(education), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to education_path(education), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_education_path,
            :class => 'btn btn-primary' %>

app/views/educations/new.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Education %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/show.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => Education %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:school_name) %></dt>
      <dd><pre class="prettyprint"><%= @education.school_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:course) %></dt>
      <dd><pre class="prettyprint"><%= @education.course %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:field_of_study) %></dt>
      <dd><pre class="prettyprint"><%= @education.field_of_study %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:year_graduated) %></dt>
      <dd><pre class="prettyprint"><%= @education.year_graduated %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              educations_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_education_path(@education), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              education_path(@education),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>